# Generated by Django 2.2 on 2019-12-09 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField(blank=True, max_length=500)),
                ('birth_date', models.DateField(blank=True, help_text='All nums (year-month-day)', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('country', models.CharField(blank=True, max_length=33)),
                ('town', models.CharField(blank=True, max_length=33)),
                ('address', models.CharField(blank=True, max_length=77)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('current_loaned_books', models.IntegerField(default=0)),
                ('total_loaned_books', models.IntegerField(default=0)),
                ('total_loaned_days', models.IntegerField(default=0)),
                ('overdue_books', models.IntegerField(default=0)),
                ('total_overdue_books_over_time', models.IntegerField(default=0)),
                ('total_overdue_days', models.IntegerField(default=0)),
                ('user_reputation', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
