# Generated by Django 2.2 on 2019-11-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a book genre (e.g. Science Fiction)', max_length=200, unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/genres')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
