# Generated by Django 2.2 on 2019-11-28 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the book language(e.g. Spanish, English, Chinese, etc)', max_length=50)),
            ],
            options={
                'verbose_name': 'Language',
            },
        ),
    ]
