# Generated by Django 2.2 on 2019-12-05 11:26

import catalog.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, validators=[catalog.validators.validate_date_not_in_future]),
        ),
        migrations.AlterField(
            model_name='author',
            name='date_of_death',
            field=models.DateField(blank=True, null=True, validators=[catalog.validators.validate_date_not_in_future], verbose_name='Died'),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(help_text='Enter a brief description of the book', max_length=1000)),
                ('isbn', models.CharField(help_text='13 characters <a href="https://www.isbn-international.org/content/what-isbn" target="_blank">ISBN number</a>', max_length=13, verbose_name='ISBN')),
                ('date_added', models.DateField(blank=True, null=True, validators=[catalog.validators.validate_date_not_in_future])),
                ('published', models.DateTimeField(blank=True, null=True, validators=[catalog.validators.validate_date_not_in_future])),
                ('copies', models.IntegerField(default=0)),
                ('loaned_copies', models.IntegerField(default=0)),
                ('available_copies', models.IntegerField(default=0)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Author')),
                ('genre', models.ManyToManyField(help_text='Select a genre for this book', to='catalog.Genre')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Language')),
            ],
        ),
    ]
