# Generated by Django 2.2 on 2019-12-05 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20191205_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, help_text='13 characters <a href="https://www.isbn-international.org/content/what-isbn" target="_blank">ISBN number</a>', max_length=13, null=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='summary',
            field=models.TextField(default='', help_text='Enter a brief description of the book', max_length=1000),
        ),
    ]
