# Generated by Django 2.2 on 2019-12-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20191205_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='available_copies',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='copies',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='loaned_copies',
            field=models.IntegerField(),
        ),
    ]
