# Generated by Django 2.2 on 2019-12-07 11:36

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20191206_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_added',
            field=models.DateField(blank=True, null=True, validators=[catalog.validators.validate_date_not_in_future]),
        ),
        migrations.AlterField(
            model_name='book',
            name='published',
            field=models.DateField(blank=True, null=True, validators=[catalog.validators.validate_date_not_in_future]),
        ),
    ]
