# Generated by Django 2.2 on 2019-12-08 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_bookinstance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={},
        ),
    ]
