# Generated by Django 2.2 on 2019-12-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_widget'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='View Count'),
        ),
    ]
