# Generated by Django 2.2 on 2019-12-21 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_language_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='View Count'),
        ),
        migrations.AddField(
            model_name='book',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='View Count'),
        ),
    ]
